/*
 * ProgressWindow.java
 *
 * Created on March 4, 2002, 3:24 PM
 */

package samples.synthesis;

import java.awt.*;

/**
 * Utility frame displaying a progress bar and a label.
 *
 */
public class ProgressWindow extends javax.swing.JFrame {
    
    /** Creates new form ProgressWindow */
    public ProgressWindow() {
	initComponents();
	Toolkit tk = Toolkit.getDefaultToolkit();
	int scw = tk.getScreenSize().width;
	int sch = tk.getScreenSize().height;
	move((scw-getSize().width)/2,(sch-getSize().height)/2);
    }
    
    public void setProgress(int progress) {
	jProgressBar1.setValue(progress);
    }
    
    public void setMessage(String msg) {
	jLabel1.setText(msg);
    }
    
    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    private void initComponents() {//GEN-BEGIN:initComponents
        jPanel1 = new javax.swing.JPanel();
        jProgressBar1 = new javax.swing.JProgressBar();
        jLabel1 = new javax.swing.JLabel();

        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowClosing(java.awt.event.WindowEvent evt) {
                exitForm(evt);
            }
        });

        jPanel1.setLayout(new java.awt.BorderLayout(20, 20));

        jPanel1.setBackground(new java.awt.Color(153, 153, 255));
        jPanel1.setBorder(new javax.swing.border.EmptyBorder(new java.awt.Insets(50, 50, 50, 50)));
        jPanel1.setPreferredSize(new java.awt.Dimension(300, 160));
        jProgressBar1.setBackground(new java.awt.Color(255, 255, 255));
        jProgressBar1.setFont(new java.awt.Font("Tahoma", 0, 12));
        jProgressBar1.setForeground(new java.awt.Color(51, 51, 255));
        jProgressBar1.setStringPainted(true);
        jPanel1.add(jProgressBar1, java.awt.BorderLayout.SOUTH);

        jLabel1.setFont(new java.awt.Font("Tahoma", 0, 12));
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("IIIIIIIIIIIIIIIIIIIIIIIIIIII");
        jPanel1.add(jLabel1, java.awt.BorderLayout.CENTER);

        getContentPane().add(jPanel1, java.awt.BorderLayout.CENTER);

        pack();
    }//GEN-END:initComponents
    
    /** Exit the Application */
    private void exitForm(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_exitForm
	System.exit(0);
    }//GEN-LAST:event_exitForm
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
	new ProgressWindow().show();
    }
    
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel jPanel1;
    private javax.swing.JProgressBar jProgressBar1;
    private javax.swing.JLabel jLabel1;
    // End of variables declaration//GEN-END:variables
    
}
