package samples.remote;

import com.cloudgarden.audio.*;

/**
 * Reports ClientEvents generated by any AudioServerSource
 */
public class TestTransferListener implements TransferListener {
    
    int total = 0;
    
    /** Issued when bytes are about to be transferred.
     * The purpose of this listener is to
     * signal when data is being transferred and to allow it to be analysed (eg, determine
     * the signal level) and also to be processed (though processing might be more cleanly
     * done by extending the AudioConnector object).
     *
     */
    public void bytesTransferred(TransferEvent evt) {
	String dirn = "WRITE";
	if(evt.getDirection() == TransferEvent.READ) dirn = "READ";
	if(evt.getLength() == -1) {
	    System.out.println("Total transfer = "+total+" bytes\n");
	} else {
	    total += evt.getLength();
	    System.out.println("Transferred "+total+" bytes (total) "+dirn);
	}
    }
    
}

