package samples.remote;

import com.cloudgarden.audio.*;

/**
 * Reports ClientEvents generated by any AudioServerSource
 */
public class TestClientListener implements ClientListener {
    
    int total = 0;
    public void clientAdded(ClientEvent evt) {
	System.out.println("client added "+evt.getClientName()+" on thread "+evt.getThread()+"\n");
    }
    public void clientRemoved(ClientEvent evt) {
	System.out.println("client removed "+evt.getClientName()+"\n");
    }
    public void bytesTransferred(ClientEvent evt) {
	String dirn = "to";
	if(evt.getDirection() == ClientEvent.FROM_CLIENT) dirn = "from";
	if(evt.getLength() == -1) {
	    System.out.println("End-of-data for client "+evt.getClientName()+" - total transfer ("+dirn+") = "+total+" bytes\n");
	} else {
	    total += evt.getLength();
	    System.out.println("transferred "+total+" bytes (total) "+dirn+" client "+evt.getClientName());
	}
    }
    
}

