/*
 * VerbalVisionTester.java
 *
 * Created on August 15, 2002, 11:18 AM
 */

package samples.accessibility;


import javax.speech.synthesis.*;

/**
 * Class to demonstrate using VerbalVision inside an application (as opposed
 * to installing it in a JVM as a java extension for all applications using that
 * JVM). To use it in an application, simply create a new VerbalVision instance
 * and call it's startUp() method. The setSynthesizer method can be used to
 * change the synthesizer used. The disable() and enable() methods can be
 * used to turn it's speech on and off.
 *
 */
public class VerbalVisionTester extends javax.swing.JFrame {
    

    Synthesizer synth;
    
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        new VerbalVisionTester().show();
    }
    
    /** Creates new form VerbalVisionTester */
    public VerbalVisionTester() {
        initComponents();

    }
    
    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    private void initComponents() {//GEN-BEGIN:initComponents
	jPanel4 = new javax.swing.JPanel();
	jPanel1 = new javax.swing.JPanel();
	jLabel1 = new javax.swing.JLabel();
	disableButton = new javax.swing.JButton();
	quitButton = new javax.swing.JButton();
	jSplitPane1 = new javax.swing.JSplitPane();
	jPanel2 = new javax.swing.JPanel();
	jScrollPane1 = new javax.swing.JScrollPane();
	jTree1 = new javax.swing.JTree();
	jPanel3 = new javax.swing.JPanel();
	jCheckBox1 = new javax.swing.JCheckBox();
	jTextField1 = new javax.swing.JTextField();
	jScrollPane3 = new javax.swing.JScrollPane();
	jTextArea1 = new javax.swing.JTextArea();
	jComboBox1 = new javax.swing.JComboBox();
	jScrollPane2 = new javax.swing.JScrollPane();
	jList1 = new javax.swing.JList();
	jMenuBar2 = new javax.swing.JMenuBar();
	jMenu2 = new javax.swing.JMenu();
	jMenuItem1 = new javax.swing.JMenuItem();
	jRadioButtonMenuItem1 = new javax.swing.JRadioButtonMenuItem();
	
	setTitle("Verbal Vision Tester");
	addWindowListener(new java.awt.event.WindowAdapter() {
	    public void windowClosing(java.awt.event.WindowEvent evt) {
		exitForm(evt);
	    }
	});
	
	jPanel4.setLayout(new java.awt.BorderLayout());
	
	jPanel4.setPreferredSize(new java.awt.Dimension(500, 250));
	jPanel1.setLayout(new java.awt.BorderLayout(5, 5));
	
	jPanel1.setBorder(new javax.swing.border.EmptyBorder(new java.awt.Insets(10, 10, 10, 10)));
	jLabel1.setBackground(new java.awt.Color(255, 255, 255));
	jLabel1.setFont(new java.awt.Font("Verdana", 1, 12));
	jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
	jLabel1.setText("Verbal Vision Tester");
	jLabel1.setBorder(new javax.swing.border.EmptyBorder(new java.awt.Insets(3, 3, 3, 3)));
	jLabel1.setOpaque(true);
	jPanel1.add(jLabel1, java.awt.BorderLayout.NORTH);
	
	disableButton.setFont(new java.awt.Font("Verdana", 1, 12));
	disableButton.setText("Disable");
	disableButton.addActionListener(new java.awt.event.ActionListener() {
	    public void actionPerformed(java.awt.event.ActionEvent evt) {
		disableButtonActionPerformed(evt);
	    }
	});
	
	jPanel1.add(disableButton, java.awt.BorderLayout.CENTER);
	
	quitButton.setFont(new java.awt.Font("Verdana", 1, 12));
	quitButton.setText("Quit");
	quitButton.addActionListener(new java.awt.event.ActionListener() {
	    public void actionPerformed(java.awt.event.ActionEvent evt) {
		quitButtonActionPerformed(evt);
	    }
	});
	
	jPanel1.add(quitButton, java.awt.BorderLayout.SOUTH);
	
	jPanel4.add(jPanel1, java.awt.BorderLayout.NORTH);
	
	jSplitPane1.setPreferredSize(new java.awt.Dimension(400, 218));
	jPanel2.setLayout(new java.awt.BorderLayout());
	
	jPanel2.setPreferredSize(new java.awt.Dimension(81, 100));
	jScrollPane1.setViewportView(jTree1);
	
	jPanel2.add(jScrollPane1, java.awt.BorderLayout.CENTER);
	
	jSplitPane1.setLeftComponent(jPanel2);
	
	jPanel3.setLayout(new javax.swing.BoxLayout(jPanel3, javax.swing.BoxLayout.Y_AXIS));
	
	jPanel3.setPreferredSize(new java.awt.Dimension(40, 216));
	jCheckBox1.setText("Do You Like Chocolate?");
	jCheckBox1.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
	jPanel3.add(jCheckBox1);
	
	jTextField1.setText("Text in a Text Field");
	jTextField1.setMaximumSize(new java.awt.Dimension(1000, 20));
	jPanel3.add(jTextField1);
	
	jScrollPane3.setHorizontalScrollBarPolicy(javax.swing.JScrollPane.HORIZONTAL_SCROLLBAR_ALWAYS);
	jScrollPane3.setVerticalScrollBarPolicy(javax.swing.JScrollPane.VERTICAL_SCROLLBAR_ALWAYS);
	jScrollPane3.setPreferredSize(new java.awt.Dimension(100, 100));
	jScrollPane3.setViewportView(jTextArea1);
	
	jPanel3.add(jScrollPane3);
	
	jPanel3.add(jComboBox1);
	
	jScrollPane2.setHorizontalScrollBarPolicy(javax.swing.JScrollPane.HORIZONTAL_SCROLLBAR_ALWAYS);
	jScrollPane2.setVerticalScrollBarPolicy(javax.swing.JScrollPane.VERTICAL_SCROLLBAR_ALWAYS);
	jScrollPane2.setPreferredSize(new java.awt.Dimension(40, 100));
	jScrollPane2.setViewportView(jList1);
	
	jPanel3.add(jScrollPane2);
	
	jSplitPane1.setRightComponent(jPanel3);
	
	jPanel4.add(jSplitPane1, java.awt.BorderLayout.CENTER);
	
	getContentPane().add(jPanel4, java.awt.BorderLayout.CENTER);
	
	jMenu2.setText("Menu");
	jMenuItem1.setText("Item");
	jMenu2.add(jMenuItem1);
	
	jRadioButtonMenuItem1.setText("RadioButton");
	jMenu2.add(jRadioButtonMenuItem1);
	
	jMenuBar2.add(jMenu2);
	
	setJMenuBar(jMenuBar2);
	
	pack();
    }//GEN-END:initComponents
    
    private void quitButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_quitButtonActionPerformed
        exitForm(null);
    }//GEN-LAST:event_quitButtonActionPerformed
    
    private void disableButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_disableButtonActionPerformed

            disableButton.setText("Enable");

    }//GEN-LAST:event_disableButtonActionPerformed
    
    /** Exit the Application */
    private void exitForm(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_exitForm

        System.exit(0);
    }//GEN-LAST:event_exitForm
    
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JMenuBar jMenuBar2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JButton disableButton;
    private javax.swing.JSplitPane jSplitPane1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JRadioButtonMenuItem jRadioButtonMenuItem1;
    private javax.swing.JButton quitButton;
    private javax.swing.JMenuItem jMenuItem1;
    private javax.swing.JList jList1;
    private javax.swing.JTextArea jTextArea1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JComboBox jComboBox1;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JCheckBox jCheckBox1;
    private javax.swing.JTree jTree1;
    // End of variables declaration//GEN-END:variables
    
}
